### ISSUE TITLE
Item Dependencies are not parsed anymore

### ISSUE THREAD

**Issue by ozontm** [stefan-baumann/ManiaPlanetSharp#24]
![image](https://user-images.githubusercontent.com/8710459/146274913-50bce793-e727-48ef-ae4c-25ef9f1dd7bd.png)

I'm expecting two dependencies here. This is broken since [27a9f4e2](https://github.com/stefan-baumann/ManiaPlanetSharp/commit/27a9f4e2181388e76a7070021867d20bd3f4667c).

**Comment by stefan-baumann** [comment]
Fixed in d51c659, thank you very much for the report and nailing down the commit that introduced it!
