### ISSUE TITLE
Icons not detected for Items

### ISSUE THREAD

**Issue by ozontm** [stefan-baumann/ManiaPlanetSharp#29]
[V_Plastic.zip](https://github.com/stefan-baumann/ManiaPlanetSharp/files/8403508/V_Plastic.zip)

Files provided by Stupskiesel.

The files from the folder "Big" were created before the update at 31st of March, 2022.
These process just fine, on MP# GameboxView AND on ItemExchange. An icon shows.

The files from the folder "Small" were created after the update at 31st of March 2022.
These process fine on MP# without errors, however, the icon is missing. This currently creates an issue on ItemExchange.

Edit: The icons for both are showing up in Trackmania.

**Comment by stefan-baumann** [comment]
Thanks for the report, I'll look into it

**Comment by stefan-baumann** [comment]
It seems they changed the format from raw uncompressed images to WebP data. I added support for that in 713d2b0fa563fca5af512d78916dd5b3f5175c8f
